name: 'quickbooks_source_integration_tests'
version: '0.6.1'

profile: 'integration_tests'
config-version: 2
models:
  quickbooks_source:
    materialized: table
    tmp:
      materialized: view
vars:
  quickbooks_schema: quickbooks_source_integrations_tests
  quickbooks_source:
    using_purchase_order: True
    using_credit_card_payment_txn: True
    
    account_identifier:                    "account_data"
    address_identifier:                    "address_data"
    bill_line_identifier:                  "bill_line_data"
    bill_linked_txn_identifier:            "bill_linked_txn_data"
    bill_payment_line_identifier:          "bill_payment_line_data"
    bill_payment_identifier:               "bill_payment_data"
    bill_identifier:                       "bill_data"
    bundle_item_identifier:                "bundle_item_data"
    bundle_identifier:                     "bundle_data"
    credit_card_payment_txn_identifier:    "credit_card_payment_txn_data"
    credit_memo_identifier:                "credit_memo_data"
    credit_memo_line_identifier:           "credit_memo_line_data"
    customer_identifier:                   "customer_data"
    department_identifier:                 "department_data"
    deposit_line_identifier:               "deposit_line_data"
    deposit_identifier:                    "deposit_data"
    estimate_identifier:                   "estimate_data"
    estimate_line_identifier:              "estimate_line_data"
    invoice_identifier:                    "invoice_data"
    invoice_line_identifier:               "invoice_line_data"
    invoice_line_bundle_identifier:        "invoice_line_bundle_data"
    invoice_linked_txn_identifier:         "invoice_linked_txn_data"
    item_identifier:                       "item_data"
    journal_entry_line_identifier:         "journal_entry_line_data"
    journal_entry_identifier:              "journal_entry_data"
    payment_identifier:                    "payment_data"
    payment_line_identifier:               "payment_line_data"
    purchase_line_identifier:              "purchase_line_data"
    purchase_order_identifier:             "purchase_order_data"
    purchase_order_line_identifier:        "purchase_order_line_data"
    purchase_order_linked_txn_identifier:  "purchase_order_linked_txn_data"
    purchase_identifier:                   "purchase_data"
    refund_receipt_line_identifier:        "refund_receipt_line_data"
    refund_receipt_identifier:             "refund_receipt_data"
    sales_receipt_line_identifier:         "sales_receipt_line_data"
    sales_receipt_identifier:              "sales_receipt_data"
    transfer_identifier:                   "transfer_data"    
    vendor_credit_line_identifier:         "vendor_credit_line_data"
    vendor_credit_identifier:              "vendor_credit_data"
    vendor_identifier:                     "vendor_data"
    
seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  quickbooks_source_integration_tests:
  
clean-targets:
- target
- dbt_modules
